import { defineConfig } from 'oxlint'

export default defineConfig({
  categories: {
    correctness: 'error',
    nursery: 'warn',
    pedantic: 'warn',
    perf: 'warn',
    restriction: 'error',
    style: 'warn',
    suspicious: 'error',
  },
  env: {
    builtin: true,
  },
  ignorePatterns: ['dist', 'node_modules', 'src-tauri', '**/*.js'],
  jsPlugins: [
    {
      name: 'vite-plus',
      specifier: 'vite-plus/oxlint-plugin',
    },
  ],
  options: {
    reportUnusedDisableDirectives: 'error',
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      files: ['vite.config.ts'],
      env: {
        node: true,
      },
    },
    {
      files: ['**/*.{ts,tsx}'],
      env: {
        browser: true,
      },
    },
  ],
  plugins: [
    'react',
    'react-perf',
    'import',
    'promise',
    'node',
    'eslint',
    'typescript',
    'unicorn',
    'oxc',
  ],
  rules: {
    'eslint/max-lines-per-function': 'off',
    'import/max-dependencies': ['warn', { max: 30 }],
    'max-statements': ['warn', { max: 30 }],
    'react/jsx-max-depth': ['error', { max: 12 }],
    'react/forbid-component-props': 'off',
    'react/jsx-no-literals': 'off',
    'react/no-multi-comp': 'off',
    'eslint/max-lines': 'off',
    'react/button-has-type': 'error',
    'react/no-array-index-key': 'off',
    'import/no-unassigned-import': 'off',
    'unicorn/prefer-global-this': 'off',
    'unicorn/no-useless-undefined': 'off',
    'typescript/no-deprecated': 'off',
    'typescript/no-misused-spread': 'off',
    'typescript/consistent-return': 'off',
    'unicorn/consistent-function-scoping': 'off',
    'import/no-nodejs-modules': 'off',
    'capitalized-comments': 'off',
    'eslint/id-length': 'off',
    'eslint/no-ternary': 'off',
    'eslint/no-void': 'off',
    'eslint/sort-imports': 'off',
    'eslint/sort-keys': 'off',
    'import/consistent-type-specifier-style': [
      'warn',
      'prefer-top-level-if-only-type-imports',
    ],
    'import/group-exports': 'off',
    'import/no-default-export': 'off',
    'import/no-named-export': 'off',
    'import/no-relative-parent-imports': 'off',
    'one-var': 'off',
    'oxc/no-async-await': 'off',
    'oxc/no-optional-chaining': 'off',
    'oxc/no-rest-spread-properties': 'off',
    'react/function-component-definition': [
      'error',
      {
        namedComponents: 'arrow-function',
        unnamedComponents: 'arrow-function',
      },
    ],
    'react/jsx-filename-extension': ['error', { extensions: ['jsx', 'tsx'] }],
    'react/react-in-jsx-scope': 'off',
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-module-boundary-types': 'off',
    'typescript/prefer-readonly-parameter-types': 'off',
    'typescript/promise-function-async': 'off',
    'unicorn/filename-case': [
      'error',
      {
        cases: {
          camelCase: true,
          pascalCase: true,
        },
      },
    ],
    'vite-plus/prefer-vite-plus-imports': 'error',
    'react-perf/jsx-no-new-object-as-prop': 'off',
    'react-perf/jsx-no-jsx-as-prop': 'off',
    'react-perf/jsx-no-new-function-as-prop': 'off',
    'unicorn/no-null': 'off',
    'eslint/no-undefined': 'off',
    'eslint/no-nested-ternary': 'off',
    'react/todo': 'off',
    'unicorn/explicit-length-check': 'off',
    'no-magic-numbers': 'off',
    'import/prefer-default-export': 'off',
    'eslint/init-declarations': 'off',
    'typescript/strict-boolean-expressions': 'off',
    'eslint/new-cap': 'off',
    'eslint/no-console': 'warn',
    'import/no-named-as-default-member': 'off',
    'unicorn/no-nested-ternary': 'off',
    'typescript/no-confusing-void-expression': 'off',
    'typescript/no-misused-promises': [
      'error',
      {
        checksVoidReturn: {
          attributes: false,
        },
      },
    ],
    'typescript/strict-void-return': 'off',
  },
})
